//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGICUwebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cour
    {
        public string numcours { get; set; }
        public string titre { get; set; }
        public Nullable<int> programme { get; set; }
        public Nullable<int> session { get; set; }
        public string prerequis { get; set; }
        public Nullable<int> heures { get; set; }
        public string description { get; set; }
    
        public virtual Programme Programme1 { get; set; }
    }
}
