//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGICUwebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public string codepermanent { get; set; }
        public string nom { get; set; }
        public string email { get; set; }
        public string mdp { get; set; }
        public string telephone { get; set; }
        public Nullable<int> session { get; set; }
        public Nullable<int> programme { get; set; }
    
        public virtual Programme Programme1 { get; set; }
    }
}
